import type { AuditMeta } from './types';
import type { Audit } from './audit';

// ── Category Config ─────────────────────────────────────────────

export interface CategoryConfig {
  id: string;
  name: string;
  /** Weight in the overall score (all weights should sum to 1.0). */
  weight: number;
}

// ── Audit Registration ──────────────────────────────────────────

export interface AuditRegistration {
  /** Construct an audit instance. */
  create: () => Audit;
  /** The audit's static meta (copied here for fast access without instantiation). */
  meta: AuditMeta;
}

export interface ScanConfig {
  categories: CategoryConfig[];
  /** categoryId → list of audit registrations */
  audits: Record<string, AuditRegistration[]>;
}

// ── Helper ──────────────────────────────────────────────────────

function reg(AuditClass: typeof Audit): AuditRegistration {
  return {
    create: () => new (AuditClass as unknown as new () => Audit)(),
    meta: AuditClass.meta,
  };
}

// ── Imports ─────────────────────────────────────────────────────

// Machine Discovery (22) — v2 taxonomy category (Plan 3, Task 5)
import {
  LlmsTxtExistsAudit,
  LlmsTxtBlockquoteAudit,
  LlmsTxtSectionsAudit,
  LlmsTxtLinkDescriptionsAudit,
  LlmsTxtLinksValidAudit,
  LlmsFullTxtAudit,
  SitemapExistsAudit,
  SitemapKeyPagesAudit,
  SitemapAbsoluteUrlsAudit,
  SitemapLastmodAudit,
  RssFeedAudit,
  RssFeedContentAudit,
  InternalLinkingAudit,
  NoBrokenLinksAudit,
  NoOrphanPagesAudit,
  LlmsTxtLinkAudit,
  RssFeedLinkAudit,
  CorsAiFilesAudit,
  CorrectContentTypesAudit,
  CacheHeadersAudit,
  NoBrokenAiEndpointsAudit,
  InternalCrossLinkingAudit,
} from './audits/machine-discovery';

// Access & Crawl Control (36) — v2 taxonomy category (Plan 3, Task 3)
import {
  NoNoindexAudit,
  NoNofollowAudit,
  NoRedirectChainsAudit,
  CanonicalLinksAudit,
  GptbotAudit,
  GoogleExtendedAudit,
  AnthropicAudit,
  PerplexitybotAudit,
  ApplebotExtendedAudit,
  CcbotAudit,
  MetaExternalAgentAudit,
  AmazonbotAudit,
  BytespiderAudit,
  CohereAiAudit,
  YoubotAudit,
  DiffbotAudit,
  Ai2botAudit,
  ChatgptUserAudit,
  ClaudeUserAudit,
  OaiSearchbotAudit,
  MetaExternalFetcherAudit,
  BravebotAudit,
  DuckassistbotAudit,
  MistralaiUserAudit,
  ClaudeSearchbotAudit,
  NoBlanketBlockAudit,
  SensitivePathsAudit,
  CrawlDelayAudit,
  MetaRobotsNotBlockingAudit,
  NoBotDetectionAudit,
  TdmRepAudit,
  AgentGovernanceAudit,
  CanonicalUrlAudit,
  AiContentDeclarationAudit,
  MetaRobotsAudit,
  HttpsEnabledAudit,
} from './audits/access-crawl-control';

// Structured Data (18)
import {
  JsonLdPresentAudit,
  SchemaValidationAudit,
  OrganizationSchemaAudit,
  WebSiteSearchActionAudit,
  BreadcrumbSchemaAudit,
  ArticleSchemaAudit,
  FaqPageSchemaAudit,
  ServiceProductSchemaAudit,
  SpeakableSchemaAudit,
  HowToSchemaAudit,
  LocalBusinessSchemaAudit,
  ReviewSchemaAudit,
  OfferSchemaAudit,
  AuthorSchemaAudit,
  ProductIdentifiersAudit,
  ProductDetailsAudit,
  ProductReviewsAudit,
  ProductTransactionCertaintyAudit,
} from './audits/structured-data';

// Meta Tags (10)
import {
  MetaDescriptionAudit,
  MetaAuthorAudit,
  UniqueMetaAudit,
  CoreOpenGraphAudit,
  OgTypeAudit,
  OgSiteNameAudit,
  OgImageAltAudit,
  TwitterCardAudit,
  OpenApiLinkAudit,
  AiCatalogLinkAudit,
} from './audits/meta-tags';

// Agent Tools (23)
import {
  OpenApiExistsAudit,
  OpenApiEndpointsAudit,
  OpenApiOperationIdsAudit,
  OpenApiServersAudit,
  OpenApiSchemasAudit,
  AiCatalogExistsAudit,
  AiCatalogMetadataAudit,
  AiCatalogUrlsAudit,
  AgentsJsonAudit,
  McpDiscoveryAudit,
  McpEndpointAudit,
  McpCapabilitiesAudit,
  ContactFormAudit,
  SearchEndpointAudit,
  NoBlockingCaptchaAudit,
  FormsNoJsAudit,
  WebmcpManifestAudit,
  WebmcpDeclarativeFormsAudit,
  WebmcpInputQualityAudit,
  WebmcpToolNamingAudit,
  WebmcpToolAnnotationsAudit,
  OpenApiDescriptionQualityAudit,
  FormActionabilityAudit,
} from './audits/agent-tools';

// Content Extraction (23) — v2 taxonomy category (Plan 3, Task 4)
import {
  FastPageLoadAudit,
  LanguageAttributeAudit,
  MarkdownAlternateAudit,
  SingleH1Audit,
  SequentialHeadingsAudit,
  MainElementAudit,
  ArticleElementAudit,
  HeaderFooterAudit,
  AsideElementAudit,
  SectionHeadingsAudit,
  SemanticListsAudit,
  DataTablesAudit,
  CodeLanguageAudit,
  TimeElementAudit,
  DefinitionElementsAudit,
  ContentDepthAudit,
  ImageAltTextAudit,
  FigureFigcaptionAudit,
  SvgBloatAudit,
  TokenRatioAudit,
  FakeHeadingsAudit,
  FastResponseTimeAudit,
  ServerRenderedAudit,
} from './audits/content-extraction';

// Accessibility — hand-rolled markup audits + engine-backed tree audits (21)
import {
  AriaLandmarksAudit,
  NavAriaLabelAudit,
  FormErrorMessagesAudit,
  A11yLandmarkUniqueAudit,
  A11yFormLabelsAudit,
  A11yAccessibleNamesAudit,
  A11yDialogNameAudit,
  A11yAriaHiddenBodyAudit,
  A11yAriaRolesAudit,
  A11yAriaAttributesAudit,
  A11yAriaRelationshipsAudit,
  A11yDuplicateIdAudit,
  A11yAutocompleteAudit,
  A11yNestedInteractiveAudit,
  A11yTableHeadersAudit,
  A11yDocumentTitleAudit,
  A11yFrameTitleAudit,
  A11yMetaRefreshAudit,
  A11yTabindexAudit,
  A11yPresentationConflictAudit,
} from './audits/accessibility';

// Technical Readiness (5)
import {
  HstsHeaderAudit,
  CspHeaderAudit,
  ContentTypeOptionsAudit,
  SecurityTxtAudit,
  CorsApiRoutesAudit,
} from './audits/technical-readiness';

// Answer Engine (11)
import {
  FaqSectionsAudit,
  QuestionHeadingsAudit,
  FirstParagraphAnswersAudit,
  DirectDefinitionsAudit,
  ComparisonTablesAudit,
  NumberedStepsAudit,
  SpecificNumbersAudit,
  DatesOnContentAudit,
  ContentWithoutClickthroughAudit,
  LastUpdatedIndicatorAudit,
  MetaDescriptionAeoAudit,
} from './audits/answer-engine';

// Generative Engine (13)
import {
  NamedAuthorAudit,
  AuthorSameAsAudit,
  AuthorPageAudit,
  AboutCredentialsAudit,
  ExternalCitationsAudit,
  BrandNameAudit,
  TrustSignalsAudit,
  ReviewSignalsAudit,
  PublicationDateAudit,
  LastModifiedSchemaAudit,
  UniqueDataAudit,
  BlockquoteUsageAudit,
  DescriptiveUrlsAudit,
} from './audits/generative-engine';

// ── Default Config ──────────────────────────────────────────────

export const defaultConfig: ScanConfig = {
  categories: [
    { id: 'machine-discovery', name: 'Machine Discovery', weight: 0.18 },
    { id: 'access-crawl-control', name: 'Access & Crawl Control', weight: 0.08 },
    { id: 'structured-data', name: 'Structured Data & Schema Markup', weight: 0.12 },
    { id: 'meta-tags', name: 'Meta Tags & AI Head Elements', weight: 0.06 },
    { id: 'agent-tools', name: 'AI Agent Tools & Action Surfaces', weight: 0.18 },
    { id: 'content-extraction', name: 'Content Extraction & Structure', weight: 0.1 },
    { id: 'accessibility', name: 'Accessibility & Agent Interaction', weight: 0.07 },
    { id: 'technical-readiness', name: 'Technical Readiness & Security', weight: 0.07 },
    { id: 'answer-engine', name: 'Answer Engine Optimization', weight: 0.07 },
    { id: 'generative-engine', name: 'Generative Engine Optimization', weight: 0.07 },
  ],
  audits: {
    'machine-discovery': [
      reg(LlmsTxtExistsAudit),
      reg(LlmsTxtBlockquoteAudit),
      reg(LlmsTxtSectionsAudit),
      reg(LlmsTxtLinkDescriptionsAudit),
      reg(LlmsTxtLinksValidAudit),
      reg(LlmsFullTxtAudit),
      reg(SitemapExistsAudit),
      reg(SitemapKeyPagesAudit),
      reg(SitemapAbsoluteUrlsAudit),
      reg(SitemapLastmodAudit),
      reg(RssFeedAudit),
      reg(RssFeedContentAudit),
      reg(InternalLinkingAudit),
      reg(NoBrokenLinksAudit),
      reg(NoOrphanPagesAudit),
      reg(LlmsTxtLinkAudit),
      reg(RssFeedLinkAudit),
      reg(CorsAiFilesAudit),
      reg(CorrectContentTypesAudit),
      reg(CacheHeadersAudit),
      reg(NoBrokenAiEndpointsAudit),
      reg(InternalCrossLinkingAudit),
    ],
    'access-crawl-control': [
      reg(NoNoindexAudit),
      reg(NoNofollowAudit),
      reg(NoRedirectChainsAudit),
      reg(CanonicalLinksAudit),
      reg(GptbotAudit),
      reg(GoogleExtendedAudit),
      reg(AnthropicAudit),
      reg(PerplexitybotAudit),
      reg(ApplebotExtendedAudit),
      reg(CcbotAudit),
      reg(MetaExternalAgentAudit),
      reg(AmazonbotAudit),
      reg(BytespiderAudit),
      reg(CohereAiAudit),
      reg(YoubotAudit),
      reg(DiffbotAudit),
      reg(Ai2botAudit),
      reg(ChatgptUserAudit),
      reg(ClaudeUserAudit),
      reg(OaiSearchbotAudit),
      reg(MetaExternalFetcherAudit),
      reg(BravebotAudit),
      reg(DuckassistbotAudit),
      reg(MistralaiUserAudit),
      reg(ClaudeSearchbotAudit),
      reg(NoBlanketBlockAudit),
      reg(SensitivePathsAudit),
      reg(CrawlDelayAudit),
      reg(MetaRobotsNotBlockingAudit),
      reg(NoBotDetectionAudit),
      reg(TdmRepAudit),
      reg(AgentGovernanceAudit),
      reg(CanonicalUrlAudit),
      reg(AiContentDeclarationAudit),
      reg(MetaRobotsAudit),
      reg(HttpsEnabledAudit),
    ],
    'structured-data': [
      reg(JsonLdPresentAudit),
      reg(SchemaValidationAudit),
      reg(OrganizationSchemaAudit),
      reg(WebSiteSearchActionAudit),
      reg(BreadcrumbSchemaAudit),
      reg(ArticleSchemaAudit),
      reg(FaqPageSchemaAudit),
      reg(ServiceProductSchemaAudit),
      reg(SpeakableSchemaAudit),
      reg(HowToSchemaAudit),
      reg(LocalBusinessSchemaAudit),
      reg(ReviewSchemaAudit),
      reg(OfferSchemaAudit),
      reg(AuthorSchemaAudit),
      reg(ProductIdentifiersAudit),
      reg(ProductDetailsAudit),
      reg(ProductReviewsAudit),
      reg(ProductTransactionCertaintyAudit),
    ],
    'meta-tags': [
      reg(MetaDescriptionAudit),
      reg(MetaAuthorAudit),
      reg(UniqueMetaAudit),
      reg(CoreOpenGraphAudit),
      reg(OgTypeAudit),
      reg(OgSiteNameAudit),
      reg(OgImageAltAudit),
      reg(TwitterCardAudit),
      reg(OpenApiLinkAudit),
      reg(AiCatalogLinkAudit),
    ],
    'agent-tools': [
      reg(OpenApiExistsAudit),
      reg(OpenApiEndpointsAudit),
      reg(OpenApiOperationIdsAudit),
      reg(OpenApiServersAudit),
      reg(OpenApiSchemasAudit),
      reg(AiCatalogExistsAudit),
      reg(AiCatalogMetadataAudit),
      reg(AiCatalogUrlsAudit),
      reg(AgentsJsonAudit),
      reg(McpDiscoveryAudit),
      reg(McpEndpointAudit),
      reg(McpCapabilitiesAudit),
      reg(ContactFormAudit),
      reg(SearchEndpointAudit),
      reg(NoBlockingCaptchaAudit),
      reg(FormsNoJsAudit),
      reg(WebmcpManifestAudit),
      reg(WebmcpDeclarativeFormsAudit),
      reg(WebmcpInputQualityAudit),
      reg(WebmcpToolNamingAudit),
      reg(WebmcpToolAnnotationsAudit),
      reg(OpenApiDescriptionQualityAudit),
      reg(FormActionabilityAudit),
    ],
    'content-extraction': [
      reg(FastPageLoadAudit),
      reg(LanguageAttributeAudit),
      reg(MarkdownAlternateAudit),
      reg(SingleH1Audit),
      reg(SequentialHeadingsAudit),
      reg(MainElementAudit),
      reg(ArticleElementAudit),
      reg(HeaderFooterAudit),
      reg(AsideElementAudit),
      reg(SectionHeadingsAudit),
      reg(SemanticListsAudit),
      reg(DataTablesAudit),
      reg(CodeLanguageAudit),
      reg(TimeElementAudit),
      reg(DefinitionElementsAudit),
      reg(ContentDepthAudit),
      reg(ImageAltTextAudit),
      reg(FigureFigcaptionAudit),
      reg(SvgBloatAudit),
      reg(TokenRatioAudit),
      reg(FakeHeadingsAudit),
      reg(FastResponseTimeAudit),
      reg(ServerRenderedAudit),
    ],
    accessibility: [
      reg(AriaLandmarksAudit),
      reg(NavAriaLabelAudit),
      reg(FormErrorMessagesAudit),
      reg(A11yLandmarkUniqueAudit),
      reg(A11yFormLabelsAudit),
      reg(A11yAccessibleNamesAudit),
      reg(A11yDialogNameAudit),
      reg(A11yAriaHiddenBodyAudit),
      reg(A11yAriaRolesAudit),
      reg(A11yAriaAttributesAudit),
      reg(A11yAriaRelationshipsAudit),
      reg(A11yDuplicateIdAudit),
      reg(A11yAutocompleteAudit),
      reg(A11yNestedInteractiveAudit),
      reg(A11yTableHeadersAudit),
      reg(A11yDocumentTitleAudit),
      reg(A11yFrameTitleAudit),
      reg(A11yMetaRefreshAudit),
      reg(A11yTabindexAudit),
      reg(A11yPresentationConflictAudit),
    ],
    'technical-readiness': [
      reg(HstsHeaderAudit),
      reg(CspHeaderAudit),
      reg(ContentTypeOptionsAudit),
      reg(SecurityTxtAudit),
      reg(CorsApiRoutesAudit),
    ],
    'answer-engine': [
      reg(FaqSectionsAudit),
      reg(QuestionHeadingsAudit),
      reg(FirstParagraphAnswersAudit),
      reg(DirectDefinitionsAudit),
      reg(ComparisonTablesAudit),
      reg(NumberedStepsAudit),
      reg(SpecificNumbersAudit),
      reg(DatesOnContentAudit),
      reg(ContentWithoutClickthroughAudit),
      reg(LastUpdatedIndicatorAudit),
      reg(MetaDescriptionAeoAudit),
    ],
    'generative-engine': [
      reg(NamedAuthorAudit),
      reg(AuthorSameAsAudit),
      reg(AuthorPageAudit),
      reg(AboutCredentialsAudit),
      reg(ExternalCitationsAudit),
      reg(BrandNameAudit),
      reg(TrustSignalsAudit),
      reg(ReviewSignalsAudit),
      reg(PublicationDateAudit),
      reg(LastModifiedSchemaAudit),
      reg(UniqueDataAudit),
      reg(BlockquoteUsageAudit),
      reg(DescriptiveUrlsAudit),
    ],
  },
};
