import type {
  ScanConditions,
  ScanReport,
} from "@forkpoint/agent-lighthouse-core";
import { buildReportView } from "./view-model";

/**
 * Generates a GitHub PR comment markdown summary.
 */
/**
 * The sentence that explains a large not-assessed count.
 *
 * "154 audits not assessed" reads as a broken scanner unless the reason sits
 * next to it.
 */
function notAssessedLine(view: ReturnType<typeof buildReportView>): string {
  const { skippedNoEvidence, noEvidenceReasons } = view.coverage;
  if (skippedNoEvidence === 0) return "";
  const why =
    noEvidenceReasons.length > 0 ? ` ${noEvidenceReasons.join(" ")}` : "";
  return `\n> **${skippedNoEvidence} audit${skippedNoEvidence === 1 ? "" : "s"} not assessed:** this scan did not obtain the evidence they need.${why}\n`;
}

function conditionsBlock(view: ReturnType<typeof buildReportView>): string {
  if (!view.conditions) return "";
  const c = view.conditions;
  const pct =
    c.coverage.registryMass > 0
      ? Math.round((c.coverage.assessedMass / c.coverage.registryMass) * 100)
      : 0;
  return `\n**Scan Conditions:**  
- **Page Type:** \`${c.pageType.type}\` (${c.pageType.source})
- **Origin Evidence:** \`${c.origin.cached ? "cached" : "fresh"}\` (version: \`${c.origin.version}\`, read at: \`${c.origin.readAt}\`)
- **Evidence Coverage:** \`${c.coverage.assessedMass} / ${c.coverage.registryMass}\` mass (${pct}%) — page: \`${c.coverage.pageMass}\`, origin: \`${c.coverage.originMass}\`, gated: \`${c.coverage.gatedMass}\`
- **Unscored Checks:** \`${c.unscored.totalCount}\` (${c.unscored.informativeCount} advisory, ${c.unscored.gatedCount} gated)${budgetLine(c.budget)}\n`;
}

/** The budget line of the conditions block, or nothing for an older report. */
function budgetLine(budget: ScanConditions["budget"]): string {
  if (!budget) return "";
  const limit = Math.round(budget.limitMs / 1000);
  const elapsed = Math.round(budget.elapsedMs / 1000);
  if (budget.limitMs === 0)
    return `\n- **Budget:** \`none\` (${elapsed} s elapsed)`;
  return budget.exhausted
    ? `\n- **Budget:** \`ran out\` at ${limit} s — ${budget.skippedCount} audits not assessed`
    : `\n- **Budget:** \`${elapsed} s\` of ${limit} s`;
}

export function generateMarkdownSummary(report: ScanReport): string {
  const view = buildReportView(report);

  const getTierEmoji = (score: number) => {
    if (score >= 90) return "🟢";
    if (score >= 70) return "🔵";
    if (score >= 50) return "🟡";
    return "🔴";
  };

  const rows = view.groups
    .flatMap((group) => {
      return group.categories.map((cat) => {
        return `| **${cat.name}** | **${cat.score} / 100** | ${getTierEmoji(cat.score)} ${cat.counts.pass}✓ ${cat.counts.warn}! ${cat.counts.fail}✗ |`;
      });
    })
    .join("\n");

  const advisory = view.groups
    .flatMap((group) => group.categories)
    .reduce((sum, cat) => sum + cat.counts.advisory, 0);

  // Without this line a reviewer sees a reported failure that moved no score
  // and has no way to tell why.
  const advisoryLine =
    advisory > 0
      ? `\n> ${advisory} advisory check${advisory === 1 ? "" : "s"} ran. They are reported but never scored.\n`
      : "";

  return `### 🗼 Agent Lighthouse Audit Report

**Target:** \`${report.url}\`  
**Overall Score:** ${
    view.overallScore === null
      ? `_Not scored_ — ${view.unscoredReason ?? "this scan obtained too little evidence to judge the site."}`
      : `**\`${view.overallScore}/100\`** *(${view.scoreTier})*`
  }  
**Pages Audited:** \`${view.pagesScanned.length}\` | **Duration:** \`${(view.durationMs / 1000).toFixed(1)}s\`
${conditionsBlock(view)}${notAssessedLine(view)}

| Category | Score | Breakdown |
| :--- | :---: | :--- |
${rows}
${advisoryLine}
*Generated by [Agent Lighthouse](https://github.com/ForkPoint/agent-lighthouse)*
`;
}
