import type { ScanReport } from '@forkpoint/agent-lighthouse-core';
import { buildReportView } from './view-model';

/**
 * Generates a GitHub PR comment markdown summary.
 */
export function generateMarkdownSummary(report: ScanReport): string {
  const view = buildReportView(report);

  const getTierEmoji = (score: number) => {
    if (score >= 90) return '🟢';
    if (score >= 70) return '🔵';
    if (score >= 50) return '🟡';
    return '🔴';
  };

  const rows = view.groups.flatMap(group => {
    return group.categories.map(cat => {
      return `| **${cat.name}** | **${cat.score} / 100** | ${getTierEmoji(cat.score)} ${cat.counts.pass}✓ ${cat.counts.warn}! ${cat.counts.fail}✗ |`;
    });
  }).join('\n');

  const advisory = view.groups
    .flatMap((group) => group.categories)
    .reduce((sum, cat) => sum + cat.counts.advisory, 0);

  // Without this line a reviewer sees a reported failure that moved no score
  // and has no way to tell why.
  const advisoryLine = advisory > 0
    ? `\n> ${advisory} advisory check${advisory === 1 ? '' : 's'} ran. They are reported but never scored.\n`
    : '';

  return `### 🗼 Agent Lighthouse Audit Report

**Target:** \`${report.url}\`  
**Overall Score:** **\`${view.overallScore}/100\`** *(${view.scoreTier})*  
**Pages Audited:** \`${view.pagesScanned.length}\` | **Duration:** \`${(view.durationMs / 1000).toFixed(1)}s\`

| Category | Score | Breakdown |
| :--- | :---: | :--- |
${rows}
${advisoryLine}
*Generated by [Agent Lighthouse](https://github.com/ForkPoint/agent-lighthouse)*
`;
}
